A simple neutron is a basic computational unit that revieves inputs, processes it, and produces an output. The following is a code for a simple neuron with three inputs

In [3]:
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2
output=inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+bias
print(output)

2.3


The main power of a neural network comes form arranging neurons together into layers, every neuron has n number of weights,, nis the no. of inputs, and 
outputs are equal to the number of neurons. 
Here,is a simple code for a 3 neuron 4 input system..

In [7]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91, 0.26, -0.5],[-0.26,-0.27,0.17, 0.87]]
bias=[2,3,0.5]
outputs=[
    inputs[0]*weights[0][0]+
    inputs[1]*weights[0][1]+
    inputs[2]*weights[0][2]+
    inputs[3]*weights[0][3]+
    bias[0],
    inputs[0]*weights[1][0]+
    inputs[1]*weights[1][1]+
    inputs[2]*weights[1][2]+
    inputs[3]*weights[1][3]+
    bias[1],
    inputs[0]*weights[2][0]+
    inputs[1]*weights[2][1]+
    inputs[2]*weights[2][2]+
    inputs[3]*weights[2][3]+
    bias[2],
]
print(outputs)

[4.8, 1.21, 2.385]


We can do the above lengthy summation efficiently using loops

In [17]:
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91, 0.26, -0.5],[-0.26,-0.27,0.17, 0.87]]
bias=[2,3,0.5]
layer_outputs=[]
for neuron_weights,neuron_bias in zip(weights,bias):
    neuron_output=0
    for inpute, weight in zip(inputs, neuron_weights):
        neuron_output+= inpute*weight
    neuron_output+=neuron_bias
    layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]


We can use the Numerical Python (numpy) library for our computions. 

In [19]:
#for a simple neuron, we will use vectorXvector dot product
import numpy as np
inputs=[1,2,3]
weights=[0.2,0.8,-0.5]
bias=2
output=np.dot(inputs,weights) + bias
print(output)

2.3


In [33]:
#for a layer of neurons, we will use vectorXmatrix dot product
inputs=[1,2,3,2.5]
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91, 0.26, -0.5],[-0.26,-0.27,0.17, 0.87]]
bias=[2,3,0.5]
ouputs= np.dot(weights,inputs)+bias
print(outputs)

[4.8, 1.21, 2.385]


In [41]:
#for a batch of neurons, we will use matrixXmatrix dot product
inputs=[[1,2,3,2.5],[0.8,2.2,2.1,3.1],[1.7,2.4,2.9,3.23]]
weights=[[0.2,0.8,-0.5,1],[0.5,-0.91, 0.26, -0.5],[-0.26,-0.27,0.17, 0.87]]
bias=[2,3,0.5]
outputs=np.dot(inputs,np.array(weights).T)+bias
print(outputs)

[[4.8    1.21   2.385 ]
 [5.97   0.394  2.752 ]
 [6.04   0.805  2.7131]]


In [1]:
import numpy as np

# Input batch (3x4)
X = np.array([
    [1,   2,   3,   2.5],
    [0.8, 2.2, 2.1, 3.1],
    [1.7, 2.4, 2.9, 3.23]
])
# Layer 1 (3x3)
W1 = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])
b1 = np.array([2, 3, 0.5])

layer1_output = np.dot(X, W1.T) + b1
print("Layer 1 output:\n", layer1_output) #3x3 output

# Layer 2
W2 = np.array([
    [0.1, 0.4, -0.3],
    [-0.2, 0.5, 0.6],
    [0.7, -0.1, 0.2]
])
b2 = np.array([1, -1, 0.2])

final_output = np.dot(layer1_output, W2.T) + b2
print("\nFinal output:\n", final_output)


Layer 1 output:
 [[4.8    1.21   2.385 ]
 [5.97   0.394  2.752 ]
 [6.04   0.805  2.7131]]

Final output:
 [[ 1.2485   0.076    3.916  ]
 [ 0.929   -0.3458   4.89   ]
 [ 1.11207 -0.17764  4.89012]]
